{% set name = "jekyll-relative-links" %}
{% set version = "0.6.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: d11301f57b39e94b6c04fff2a3b145fe2f6a27be631a403e2542fa2e1548dd6d

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-jekyll >=3.3,<4

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: A Jekyll plugin to convert relative links to markdown files to their rendered equivalents.

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/benbalter/{{ name }}

extra:
  recipe-maintainers:
    - sodre
