travis:
  secure:
    BINSTAR_TOKEN: hj0PL33awzDe1kIcdeStc1JC0ETOAP0gWMNAYHbCcn6ijR1jr6qwLfWP0WXtOoqyys5d1li9TEaYWwAQhl1/retkf+opt3Uv0z99A/VjMviCufSZSMimF3XPuW0cP/NpuLVhliPIN+oVrQjHAwK1ioGtsihHXVlkIuJFrH1o4Jxu+jSWkAGEfye/nFYeVezUm39vK0Bxr108X2cB3Y6Yf5Ne/HUcum6l+5pghF3Njo92PwRlvoIyr8nmSoSp23+KuwSGF2+B8hzdhHPVVM1EfvhDDKoyu+HUNXrGbRyVBY2OHxCM79Q6DFDcIbr3dmAGNaEdj9HmpmIVUkHLA11vUKYnRnPb1IYORrzkNPrPJoPEjJupjOElTYrY/yxHvK9PK8ICbH/V6zZBtCuUOPqXhxOGg+adKDDCNehFrXsS8hn2jejdoppwwq2fTptU8XZiFfIsBUjiisCEtArVd3I3M83cYBx7nt7AgqxgrhLoDQWvwCJj+viV/pX3lQ+A9RV8Vb7r5YBsjBoycgtCIuvxO13gjPhPhLXt6WA1Z9YBpHqnxL1o075mEoLB4/fT8ly8IDqkTjDGDNUFi1uwly9ls6Zad9TapnncTPrdszFXKrzki0JNjFGU8miXG0od424HbfWHG4vWA3N5W5Yf9tkAWPPjy3Xbwu7z318mfNboaUs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
